---
# build_arg_defaults
ee_container_runtime: podman
ee_version: 3


ee_stream: "{% if ee_base_registry_username is defined %}downstream{% else %}upstream{% endif %}"

# Image defaults
ee_base_image: "{{ __ee_stream_images[ee_stream].base_image }}"
ee_registry_username: "{{ ee_base_registry_username | default(omit, true) }}"
ee_registry_password: "{{ ee_base_registry_password | default(omit, true) }}"

# Req File defaults
ansible_cfg_file: ansible.cfg

# Default EE list
ee_list: []

# Major section Options
ee_build_options: "{{ __ee_dnf_fix[ee_stream] }}"
ee_build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vv'

# Controls
ee_image_push: true
ee_update_base_images: true
# mark as breaking change
ee_pull_collections_from_hub: true
ee_builder_dir_clean: true
ee_validate_certs: false
ee_prune_images: true
ee_create_controller_def: false

# Registry
# name
# ee_registry_username
# ee_registry_password
# ee_registry_dest

# Hub host variables for ansible.cfgw
ee_ah_host: "{{ ah_host }}"
ee_ah_token: "{{ ah_token }}"
...
